<?php

namespace AppBundle\Repository;

/**
 * JournalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JournalRepository extends \Doctrine\ORM\EntityRepository
{
    public function findList()
    {
        return $this->createQueryBuilder('j')
                    ->where('j.statut = 1')
                    ->andWhere('j.dateEvent >= :date')
                    ->orderBy('j.dateEvent', 'ASC')
                    ->addOrderBy('j.debut', 'ASC')
                    ->setParameters([
                        'date'=> date('Y-m-d', time()),
                    ])
                    ->getQuery()->getResult()
            ;
    }

    /**
     *
     */
    public function findActiviteEncours()
    {
        $temps = time() - (2*60*60);
        return $this->createQueryBuilder('j')
                    ->where('j.statut = 1')
                    ->andWhere('j.dateEvent = :date')
                    ->andWhere(':periode BETWEEN j.debut AND j.fin')
                    ->setParameters([
                        'date'=> date('Y-m-d', time()),
                        'periode' => date('H:i', $temps)
                    ])
                    ->getQuery()->getResult()
            ;
    }
}
